parameters:
  app.entity.user.class: AppBundle\Entity\User

  app.repository.user.class: AppBundle\Repository\UserRepository

services:
  app.repository.abstract:
    abstract: true
    factory: ["@doctrine.orm.entity_manager", getRepository]
    
  app.repository.user:
    parent: app.repository.abstract
    class: %app.repository.user.class%
    arguments: [ %app.entity.user.class% ]






