parameters:
  app.listener.exception.class: AppBundle\Listener\ExceptionListener
  
services:
  app.listener.exception:
    class: %app.listener.exception.class%
    arguments: ["@service_container"]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    calls:
      - [ setLogger, [ '@logger'] ]

  